replicaCount: 1

image:
  repository: products-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

serviceAccountName: products-service

serviceAccountAnnotations:
  eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/your-iam-role
  example.com/custom: custom-value


AWS_REGION: us-west-2
PRODUCTS_TABLE: products
PORT: "8080"
TEMPO_ENDPOINT: tempo:4318