apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "products-service.fullname" . }}
  labels:
    app: {{ include "products-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "products-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "products-service.name" . }}
    spec:
      containers:
        - name: products-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: AWS_REGION
              value: "us-west-2"
            - name: PRODUCTS_TABLE
              value: "products"