apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-backoffice
  labels:
    app: ui-backoffice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ui-backoffice
  template:
    metadata:
      labels:
        app: ui-backoffice
    spec:
      containers:
        - name: ui-backoffice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: PRODUCT_API_BASE_URL
              value: {{ .Values.PRODUCT_API_BASE_URL | quote }}
            - name: ORDER_API_BASE_URL
              value: {{ .Values.ORDER_API_BASE_URL | quote }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
            - name: NODE_ENV
              value: {{ .Values.NODE_ENV | quote }}